name: arkit_plugin
description: Flutter Plugin for ARKit - Apple's augmented reality (AR) development platform for iOS mobile devices.
version: 0.6.2
author: Oleksandr Leuschenko <olexa.le@gmail.com>
homepage: https://github.com/olexale/arkit_flutter_plugin

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  vector_math: ^2.1.0
  json_annotation: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  json_serializable: ^4.1.0
  pedantic: ^1.11.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: ArkitPlugin
